ALTER TABLE "Barbershop" ADD COLUMN IF NOT EXISTS "openTime" TEXT NOT NULL DEFAULT '09:00';
ALTER TABLE "Barbershop" ADD COLUMN IF NOT EXISTS "closeTime" TEXT NOT NULL DEFAULT '18:00';
ALTER TABLE "Barbershop" ADD COLUMN IF NOT EXISTS "slotMinutes" INTEGER NOT NULL DEFAULT 30;
